/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

val defaultJdkVersion = 17
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}


buildscript {
    repositories {
        mavenCentral()
        maven{ url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/") }
    }
}

plugins {
    idea
    `java-library`
    `maven-publish`
    signing
   // checkstyle
    id("com.diffplug.spotless") version "7.0.2"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("com.google.protobuf") version "0.9.5"
    id("java-test-fixtures")
}

group = "com.clickhouse.kafka"
version = file("VERSION").readText().trim()
description = "The official ClickHouse Apache Kafka Connect Connector."

repositories {
    mavenCentral()
    mavenLocal()
    maven("https://packages.confluent.io/maven/")
    maven("https://jitpack.io")
}

extra.apply {
    set("clickHouseDriverVersion", "0.9.2")
    set("kafkaVersion", "2.7.0")
    set("gson", "2.13.1")
    set("jackson", "2.19.1")

    // Testing dependencies
    set("junitJupiterVersion", "5.9.2")
    set("junitPlatformVersion", "1.8.1")
    set("hamcrestVersion", "2.2")
    set("mockitoVersion", "4.0.0")

    // Integration test dependencies
    set("confluentVersion", "6.0.1")
    set("scalaVersion", "2.13")
    set("curatorVersion", "2.9.0")
    set("connectUtilsVersion", "0.4+")

    // Test extra test dependencies
    set("kafkaPlatformSchemaRegistry", "7.9.1")
    set("kafkaPlatformProtobuf", "7.9.1")
    set("testcontainers", "1.21.3")
    set("toxiproxy", "1.21.0")
    set("org.json", "20250517")
    set("libprotobuf", "3.25.8")
}

val clickhouseDependencies: Configuration by configurations.creating


dependencies {
    implementation("org.apache.kafka:connect-api:${project.extra["kafkaVersion"]}")
    implementation("com.clickhouse:clickhouse-client:${project.extra["clickHouseDriverVersion"]}")
    implementation("com.clickhouse:clickhouse-http-client:${project.extra["clickHouseDriverVersion"]}")
    implementation("com.clickhouse:clickhouse-data:${project.extra["clickHouseDriverVersion"]}")
    implementation("com.clickhouse:client-v2:${project.extra["clickHouseDriverVersion"]}")
    implementation("com.google.code.gson:gson:${project.extra["gson"]}")

    implementation("org.apache.httpcomponents.client5:httpclient5:5.5")

    // Avoid telescoping constructors problem with the builder pattern using Lombok
    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    // To parse JSON response from ClickHouse to parse complex data types correctly
    implementation("com.fasterxml.jackson.core:jackson-core:${project.extra["jackson"]}")
    implementation("com.fasterxml.jackson.core:jackson-databind:${project.extra["jackson"]}")
    implementation("com.fasterxml.jackson.core:jackson-annotations:${project.extra["jackson"]}")

    /*
        Will in side the Confluent Archive
     */
    clickhouseDependencies("org.apache.httpcomponents.client5:httpclient5:5.5")
    clickhouseDependencies("com.clickhouse:clickhouse-client:${project.extra["clickHouseDriverVersion"]}")
    clickhouseDependencies("com.clickhouse:client-v2:${project.extra["clickHouseDriverVersion"]}")
    clickhouseDependencies("com.clickhouse:clickhouse-http-client:${project.extra["clickHouseDriverVersion"]}")
    clickhouseDependencies("com.google.code.gson:gson:${project.extra["gson"]}")
    clickhouseDependencies("com.fasterxml.jackson.core:jackson-core:${project.extra["jackson"]}")
    clickhouseDependencies("com.fasterxml.jackson.core:jackson-databind:${project.extra["jackson"]}")
    clickhouseDependencies("com.fasterxml.jackson.core:jackson-annotations:${project.extra["jackson"]}")

    // Unit Tests
    testImplementation(platform("org.junit:junit-bom:${project.extra["junitJupiterVersion"]}"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-runner")
    testImplementation("org.apiguardian:apiguardian-api:1.1.2") // https://github.com/gradle/gradle/issues/18627
    testImplementation("org.hamcrest:hamcrest:${project.extra["hamcrestVersion"]}")
    testImplementation("org.mockito:mockito-junit-jupiter:${project.extra["mockitoVersion"]}")

    // IntegrationTests
    testImplementation("org.testcontainers:clickhouse:${project.extra["testcontainers"]}")
    testImplementation("org.testcontainers:kafka:${project.extra["testcontainers"]}")
    testImplementation("com.squareup.okhttp3:okhttp:4.12.0")
    testImplementation("org.json:json:${project.extra["org.json"]}")
    testImplementation("org.testcontainers:toxiproxy:${project.extra["toxiproxy"]}")
    testImplementation("org.apache.httpcomponents.client5:httpclient5:5.5")
    testImplementation("com.clickhouse:clickhouse-jdbc:${project.extra["clickHouseDriverVersion"]}:all")
    testImplementation("com.clickhouse:clickhouse-client:${project.extra["clickHouseDriverVersion"]}")
    testImplementation("com.clickhouse:client-v2:${project.extra["clickHouseDriverVersion"]}")
    testImplementation("com.clickhouse:clickhouse-http-client:${project.extra["clickHouseDriverVersion"]}")


//    // Schema Registry client for testing
    testImplementation("io.confluent:kafka-schema-registry-client:${project.extra["kafkaPlatformSchemaRegistry"]}")
    testImplementation("io.confluent:kafka-schema-registry:${project.extra["kafkaPlatformSchemaRegistry"]}")
    testImplementation("io.confluent:kafka-schema-serializer:${project.extra["kafkaPlatformSchemaRegistry"]}")

    // Test Fixtures Dependencies
    // Test Fixtures is used to extract helpers into a separate jar and publish locally to use in other test projects
    // like JMH Benchmark
    // Protobuf dependencies
    testFixturesApi("com.google.protobuf:protobuf-java:${project.extra["libprotobuf"]}")
    testFixturesApi("io.confluent:kafka-protobuf-serializer:${project.extra["kafkaPlatformProtobuf"]}")
    testFixturesApi("io.confluent:kafka-connect-protobuf-converter:${project.extra["kafkaPlatformProtobuf"]}")
    testFixturesApi("io.confluent:kafka-connect-avro-converter:7.9.1")
    testFixturesApi("io.confluent:kafka-avro-serializer:7.9.1")

    testFixturesImplementation(platform("org.junit:junit-bom:${project.extra["junitJupiterVersion"]}"))
    testFixturesImplementation("org.junit.jupiter:junit-jupiter")
    testFixturesImplementation("org.junit.platform:junit-platform-runner")
    testFixturesImplementation("org.apache.kafka:connect-api:${project.extra["kafkaVersion"]}")
    testFixturesImplementation("org.apache.commons:commons-lang3:3.18.0")
    testFixturesImplementation("com.clickhouse:clickhouse-client:${project.extra["clickHouseDriverVersion"]}")
    testFixturesImplementation("com.clickhouse:clickhouse-http-client:${project.extra["clickHouseDriverVersion"]}")
    testFixturesImplementation("com.clickhouse:clickhouse-data:${project.extra["clickHouseDriverVersion"]}")
    testFixturesImplementation("com.clickhouse:client-v2:${project.extra["clickHouseDriverVersion"]}")
    testFixturesImplementation("com.google.code.gson:gson:${project.extra["gson"]}")
    testFixturesImplementation("org.json:json:${project.extra["org.json"]}")
}


sourceSets.create("integrationTest") {
    java.srcDir("src/integrationTest/java")
    compileClasspath += sourceSets["main"].output + configurations["testRuntimeClasspath"]
    runtimeClasspath += output + compileClasspath + sourceSets["test"].runtimeClasspath
}
tasks.create("integrationTest", Test::class.java) {
    description = "Runs the integration tests"
    group = "verification"
    testClassesDirs = sourceSets["integrationTest"].output.classesDirs
    classpath = sourceSets["integrationTest"].runtimeClasspath
    outputs.upToDateWhen { false }
    dependsOn("prepareConfluentArchive")
    mustRunAfter("test")
    systemProperties = System.getProperties() as Map<String, Any>
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("-Xlint:unchecked", "-Xlint:deprecation"))
}

tasks.withType<Test> {
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1
    tasks.getByName("check").dependsOn(this)
    systemProperty("file.encoding", "windows-1252") // run tests with different encoding
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
    testLogging.exceptionFormat = TestExceptionFormat.FULL
    val javaVersion: Int = (project.findProperty("javaVersion") as String? ?: defaultJdkVersion.toString()).toInt()
    logger.info("Running tests using JDK$javaVersion")
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(javaVersion))
    })

    systemProperties(mapOf("com.clickhouse.test.uri" to System.getProperty("com.clickhouse.test.uri", "")))

    val jdkHome = project.findProperty("jdkHome") as String?
    jdkHome.let {
        val javaExecutablesPath = File(jdkHome, "bin/java")
        if (javaExecutablesPath.exists()) {
            executable = javaExecutablesPath.absolutePath
        }
    }

    addTestListener(object : TestListener {
        override fun beforeTest(testDescriptor: TestDescriptor?) {}
        override fun beforeSuite(suite: TestDescriptor?) {}
        override fun afterTest(testDescriptor: TestDescriptor?, result: TestResult?) {}
        override fun afterSuite(d: TestDescriptor?, r: TestResult?) {
            if (d != null && r != null && d.parent == null) {
                val resultsSummary = """Tests summary:
                    | ${r.testCount} tests,
                    | ${r.successfulTestCount} succeeded,
                    | ${r.failedTestCount} failed,
                    | ${r.skippedTestCount} skipped""".trimMargin().replace("\n", "")

                val border = "=".repeat(resultsSummary.length)
                logger.lifecycle("\n$border")
                logger.lifecycle("Test result: ${r.resultType}")
                logger.lifecycle(resultsSummary)
                logger.lifecycle("${border}\n")
            }
        }
    })
}

/*
 * ShadowJar
 */
tasks.withType<Jar> {
    manifest {
        attributes["Implementation-Title"] = "ClickHouse-Kafka-Connect"
        attributes["Implementation-Version"] = project.version.toString()
    }
}
tasks.register<ShadowJar>("confluentJar") {
    archiveClassifier.set("confluent")
    from(clickhouseDependencies, sourceSets.main.get().output)
}

/*
tasks.register<ShadowJar>("allJar") {
    archiveClassifier.set("all")
    from(clickhouseDependencies, sourceSets.main.get().output)
}
*/


// Confluent Archive
val releaseDate by extra(DateTimeFormatter.ISO_LOCAL_DATE.format(LocalDateTime.now()))
val archiveFilename = "clickhouse-kafka-connect"
tasks.register<Copy>("prepareConfluentArchive") {
    group = "Confluent"
    description = "Prepares the Confluent Archive ready for the hub"
    dependsOn("confluentJar")

    val baseDir = "$archiveFilename-${project.version}"
    from("config/archive/manifest.json") {
        expand(project.properties)
        destinationDir = file("$buildDir/confluentArchive/$baseDir")
    }

    from("config/archive/assets") {
        into("assets")
    }

    from("$buildDir/libs") {
        include(listOf("${project.name}-${project.version}-confluent.jar"))
        into("lib")
    }

    from(".") {
        include(listOf("README.md", "LICENSE"))
        into("doc")
    }
}

tasks.register<Zip>("createConfluentArchive") {
    group = "Confluent"
    description = "Creates the Confluent Archive zipfile to be uploaded to the Confluent Hub"
    dependsOn("prepareConfluentArchive")
    from(files("$buildDir/confluentArchive"))
    archiveBaseName.set("")
    archiveAppendix.set(archiveFilename)
    archiveVersion.set(project.version.toString())
    destinationDirectory.set(file("$buildDir/confluent"))
}

var generateVersionFile = tasks.register<DefaultTask>("generateVersionFile") {
    val outputDir = "generated/sources/version/java/main/com/clickhouse/kafka/connect/sink/";
    outputs.dir(layout.buildDirectory.dir(outputDir))
    doFirst {
        val outputDir = layout.buildDirectory.dir(outputDir).get().asFile
        outputDir.mkdirs() // Ensure the directory exists

        val outputFile = File(outputDir, "Version.java")
        val versionContent = """
package com.clickhouse.kafka.connect.sink;

public final class Version {
    public static final String ARTIFACT_VERSION = "${project.version}";

    private Version() {
        // Prevent instantiation
    }
}
""".trimIndent()

        outputFile.writeText(versionContent)
    }
}
tasks.getByName("compileJava").dependsOn("generateVersionFile")

sourceSets {
    main {
        java {
            srcDir(generateVersionFile)
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${project.extra["libprotobuf"]}"
    }
//    generatedFilesBaseDir = "$buildDir/generated/source/proto"
}

task("testJar", type = Jar::class) {
    archiveClassifier.set("test")
    from(sourceSets.testFixtures.get().allSource)
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"]) // Publishes the Java component
        }
        create<MavenPublication>("mavenTestJar") {
            artifact(tasks["testJar"])
        }
    }
}

