/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "clickhouse-kafka-connect"
