---
x-ch-common: &ch-common
#  TODO: add different settings files for different CH versions as necessary (see dbt-clickhouse for reference)
  volumes:
    - /var/lib/clickhouse
    - type: bind
      source: ${PROJECT_ROOT:-.}/users.xml
      target: /etc/clickhouse-server/users.d/users.xml
    - type: bind
      source: ${PROJECT_ROOT:-.}/config.xml
      target: /etc/clickhouse-server/config.d/config.xml
  ulimits:
    nofile:
      soft: 262144
      hard: 262144

services:
  ch0:
    image: clickhouse/clickhouse-server:${CH_VERSION:-latest}
    environment:
      - SERVER_INDEX=1
      - SHARD_NUM=${SHARD_NUM:-1}
      - REPLICA_NUM=${REPLICA_NUM:-1}
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ports:
      - "8123:8123"
      - "8443:8443"
      - "9000:9000"
      #  for local docker tests
      - "10723:8123"
      - "10743:8443"
      - "10900:9000"
    <<: *ch-common
  ch1:
    image: clickhouse/clickhouse-server:${CH_VERSION:-latest}
    environment:
      - SERVER_INDEX=2
      - SHARD_NUM=${SHARD_NUM:-2}
      - REPLICA_NUM=${REPLICA_NUM:-2}
      - CLICKHOUSE_SKIP_USER_SETUP=1
    <<: *ch-common
  ch2:
    image: clickhouse/clickhouse-server:${CH_VERSION:-latest}
    environment:
      - SERVER_INDEX=3
      - SHARD_NUM=${SHARD_NUM:-3}
      - REPLICA_NUM=${REPLICA_NUM:-3}
      - CLICKHOUSE_SKIP_USER_SETUP=1
    <<: *ch-common
