/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.clickhouse.kafka.connect.avro.test;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3455267125182295158L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.clickhouse.kafka.connect.avro.test\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"time1\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"time2\",\"type\":{\"type\":\"int\",\"logicalType\":\"time-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimeMillisConversion());
  }

  private static final BinaryMessageEncoder<Event> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Event> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Event> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Event> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Event> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Event to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Event from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Event instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Event fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.time.Instant time1;
  private java.time.LocalTime time2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Event() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param time1 The new value for time1
   * @param time2 The new value for time2
   */
  public Event(java.lang.Long id, java.time.Instant time1, java.time.LocalTime time2) {
    this.id = id;
    this.time1 = time1.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.time2 = time2.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return time1;
    case 2: return time2;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimeMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: time1 = (java.time.Instant)value$; break;
    case 2: time2 = (java.time.LocalTime)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'time1' field.
   * @return The value of the 'time1' field.
   */
  public java.time.Instant getTime1() {
    return time1;
  }


  /**
   * Sets the value of the 'time1' field.
   * @param value the value to set.
   */
  public void setTime1(java.time.Instant value) {
    this.time1 = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'time2' field.
   * @return The value of the 'time2' field.
   */
  public java.time.LocalTime getTime2() {
    return time2;
  }


  /**
   * Sets the value of the 'time2' field.
   * @param value the value to set.
   */
  public void setTime2(java.time.LocalTime value) {
    this.time2 = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new Event RecordBuilder.
   * @return A new Event RecordBuilder
   */
  public static com.clickhouse.kafka.connect.avro.test.Event.Builder newBuilder() {
    return new com.clickhouse.kafka.connect.avro.test.Event.Builder();
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Event RecordBuilder
   */
  public static com.clickhouse.kafka.connect.avro.test.Event.Builder newBuilder(com.clickhouse.kafka.connect.avro.test.Event.Builder other) {
    if (other == null) {
      return new com.clickhouse.kafka.connect.avro.test.Event.Builder();
    } else {
      return new com.clickhouse.kafka.connect.avro.test.Event.Builder(other);
    }
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Event instance.
   * @param other The existing instance to copy.
   * @return A new Event RecordBuilder
   */
  public static com.clickhouse.kafka.connect.avro.test.Event.Builder newBuilder(com.clickhouse.kafka.connect.avro.test.Event other) {
    if (other == null) {
      return new com.clickhouse.kafka.connect.avro.test.Event.Builder();
    } else {
      return new com.clickhouse.kafka.connect.avro.test.Event.Builder(other);
    }
  }

  /**
   * RecordBuilder for Event instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private long id;
    private java.time.Instant time1;
    private java.time.LocalTime time2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.clickhouse.kafka.connect.avro.test.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.time1)) {
        this.time1 = data().deepCopy(fields()[1].schema(), other.time1);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.time2)) {
        this.time2 = data().deepCopy(fields()[2].schema(), other.time2);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Event instance
     * @param other The existing instance to copy.
     */
    private Builder(com.clickhouse.kafka.connect.avro.test.Event other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.time1)) {
        this.time1 = data().deepCopy(fields()[1].schema(), other.time1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.time2)) {
        this.time2 = data().deepCopy(fields()[2].schema(), other.time2);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'time1' field.
      * @return The value.
      */
    public java.time.Instant getTime1() {
      return time1;
    }


    /**
      * Sets the value of the 'time1' field.
      * @param value The value of 'time1'.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder setTime1(java.time.Instant value) {
      validate(fields()[1], value);
      this.time1 = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'time1' field has been set.
      * @return True if the 'time1' field has been set, false otherwise.
      */
    public boolean hasTime1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'time1' field.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder clearTime1() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'time2' field.
      * @return The value.
      */
    public java.time.LocalTime getTime2() {
      return time2;
    }


    /**
      * Sets the value of the 'time2' field.
      * @param value The value of 'time2'.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder setTime2(java.time.LocalTime value) {
      validate(fields()[2], value);
      this.time2 = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'time2' field has been set.
      * @return True if the 'time2' field has been set, false otherwise.
      */
    public boolean hasTime2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'time2' field.
      * @return This builder.
      */
    public com.clickhouse.kafka.connect.avro.test.Event.Builder clearTime2() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Event build() {
      try {
        Event record = new Event();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.time1 = fieldSetFlags()[1] ? this.time1 : (java.time.Instant) defaultValue(fields()[1]);
        record.time2 = fieldSetFlags()[2] ? this.time2 : (java.time.LocalTime) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Event>
    WRITER$ = (org.apache.avro.io.DatumWriter<Event>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Event>
    READER$ = (org.apache.avro.io.DatumReader<Event>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










