name: Build Against ClickHouse Head

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  # Run the CI test suite against the head (nightly) build of the ClickHouse server.
  clickhouse-head:
    name: ClickHouse head
    uses: ./.github/workflows/tests.yaml
    with:
      clickhouse_version: head
    secrets: inherit

  # Build the head of clickhouse-java from source and run the CI test suite against it.
  clickhouse-java-head:
    name: clickhouse-java head
    uses: ./.github/workflows/tests.yaml
    with:
      clickhouse_version: latest
      clickhouse_java: main
      run_cloud_tests: true
    secrets: inherit
